In [3]:
""" Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde."""

import numpy as np

array = np.array([1,2,3,4,5,6])
size = 6
output_matrix = np.column_stack([array**(size-i-1) for i in range(size)])
print(output_matrix)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


In [6]:
"""Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3."""

import numpy as np

def moving_avg(arr, num):
    arr_sum = np.cumsum(arr)
    arr_sum[num:] = arr_sum[num:]- arr_sum[:-num]
    return arr_sum[num-1:]/num

array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
np.array(moving_avg(array, 3))

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])